name: "Publish to crates.io"
on:
  pull_request:
    branches:
      - 'master'
    types:
      - closed
    paths:
      - 'Cargo.toml'
  push:
    branches:
      - 'master'
    paths:
      - 'Cargo.toml'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: swatinem/rust-cache@v2
        name: Publish
        run: >
          cargo publish
          --verbose
          --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
          --all-features
